# Spring
spring:
  config:
    import:
      - env.properties
      - optional:env.yml
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    check-template-location: false
  mvc:
    log-request-details: true

# Logging
logging:
  level:
    web: trace
    com.battlecruisers.yanullja: trace
    org:
      hibernate:
        sql: trace
        type.descriptor.sql: debug
      springframework: info
      springframework.web: trace
    root: info

# Logbook
logbook:
  format:
    style: http
  write:
    max-body-size: 1024
